locale-UI/fr.po
locale/fr.po

hi,
this is updated translation files for french.
How can i test it and ensure it s bugless ?

update french translation

---

EasyScreenCast.gtkbuilder

Cleaned up the langauge in Options

---

.gitignore
gulpfile.js
package.json

Changes to be committed:
new file:   .gitignore
new file:   gulpfile.js
new file:   package.json

Add gulp task for javascript linting

---

EasyScreenCast.gtkbuilder
README.md
metadata.json

@iacopodeenosee Is it ok to tag 0.9.9 after this merge on Github? Is that also the version on extensions.gnome.org? Should we maybe include the version number on the description there?

Finalize new version

---

.eslintrc.json
convenience.js
extension.js
prefs.js
selection.js
utilrecorder.js
utilwebcam.js

I think it would be good to set some rules for the code style, so future contributions know what to aim for. The code usually prefers curly brackets, so that is the first rule I added to an eslintrc file and adapted the code style accordingly.

Code style, Require curly brackets

---

selection.js

Hello,
I started using this tool and noticed that there were two grammar errors ("a" vs "an"). This PR just fixes those issues.

Fix grammar

---

locale/fr.po

I translated a lot of missing translations.

French translation

---

Makefile

Clean the .mo files generated under locale/

Improve the clean target

---

.eslintrc.json
.eslintrc.yml
CHANGELOG.md
Makefile
convenience.js
display_module.js
extension.js
lint/README.md
lint/eslintrc-gjs.yml
lint/eslintrc-shell.yml
package-lock.json
package.json
prefs.js
selection.js
settings.js
timer.js
utilaudio.js
utilexecmd.js
utilgsp.js
utilnotify.js
utilrecorder.js
utilwebcam.js

* Fixes first point of #299 
* Fixes #130

Add eslint rules

---

CHANGELOG.md
extension.js
utilnotify.js

Fix notification

---

extension.js
utilwebcam.js

Filter webcam devices list by devicePath property

---

Options_UI.glade
Options_UI.glade-gtk4
extension.js
locale/ca.po
locale/de.po
locale/easyscreencast.pot
locale/es.po
locale/fr.po
locale/it.po
locale/ja.po
locale/pt_BR.po
locale/ru.po
locale/uk.po
locale/vi.po

when settings is changed.
- Fixes #311

Enable or disable keybinding immediately

---

utilexecmd.js

Logfiles under the support tag weren't shown anymore

---

Options_UI.glade
Options_UI.glade-gtk4
prefs.js
utilgsp.js

Add new file container and presets for mp4+aac

---

README.md
metadata.json

Add Gnome Shell 42 support

---

convenience.js
extension.js
metadata.json
prefs.js
selection.js
settings.js
utilaudio.js
utilgsp.js
utilnotify.js
utilrecorder.js
utilwebcam.js

Remove global object instances

---

CHANGELOG.md
prefs.js
utilrecorder.js

Fix file folder selection

---

.github/workflows/node.js.yml
metadata.json
package-lock.json
package.json
selection.js

Gnome 44 is there: https://release.gnome.org/44/
https://gjs.guide/extensions/upgrading/gnome-shell-44.html

Add Gnome Shell 44 support

---

CHANGELOG.md
extension.js

Unregister Mixer Control when extension is disabled

---

CHANGELOG.md
utilwebcam.js

Fix device.get_properties() is null

---

CHANGELOG.md
extension.js
utilwebcam.js

Initialize Gst/CtrlWebcam lazily
