EasyScreenCast/EasyScreenCast

- extension.js
Abbreviating “seconds” as it’s not common to write out the full word. Would be nice to conserve some width in this UI. Leaving logic for plural forms in place even though it’s not needed for English, as other languages may still need it.
I agree with the project license and for this pull request to be distributed under the terms of the project’s license.
> Change weirdly phrased str for delayed recordings

- metadata.json
I have tested this on my Arch Linux with Gnome Shell 3.20 and it is working fine.
> Added support for Gnome Shell 3.20

- selection.js
- utilwebcam.js
the first patch is a generic fix. That is cleanCapsOPT does not return anything if a brace matches.
alas the fourth, fifth and sixth  ones which revolves around window selection record fxes.
Fourth : extends the debugging output to show  that getWindowRectangle returns undefined values in its current state.
Fifth: fixes getWindowRectange to returns the values : x, y, width and height.
Sixth: to cast wx and wy the x and y top left position of the window to positive values as otherwise the recording workflow complains about invalid params. 
The second and third ones are more specific to a use case. That is my caps includes colorimetry.
The colorimetry holds its value inside brace but this one is not a range.
The second patch  handles the "allocation size overflow" error that ensue from …
> Fix windowselection

- metadata.json
The plugin seems to work with Gnome Shell 3.22.
Changes to be committed:
modified:   metadata.json
> Metadata: Add 3.22 shell

- extension.js
Currently opening the extension menu will log warnings about
the menu box layout.
Attempting to add actor of type 'StBoxLayout' to a
container of type 'StBoxLayout', but the actor has
already a parent of type 'StBoxLayout'.
This commit moves the creation of the audio recording menu
to the init function, so it is not recreated on each
refresh when opening the extension menu. Now only the
submenu items are refreshed.
Fixes #72
> Fix Clutter warnings when opening the extension menu

- convenience.js
- extension.js
- prefs.js
- selection.js
- settings.js
- utilaudio.js
- utilgsp.js
- utilnotify.js
- utilrecorder.js
- utilwebcam.js
To avoid importing and registering the prefs window from the extension,
which breaks gnome-shell when it reloads the extension.
Fixes #46
> Split settings handling from prefs window

- .github/ISSUE_TEMPLATE.md
Added a header to the display server entry. This makes it easier to search for display-specific issues. (Otherwise a search for "Wayland" returns all issues.)
> Update "Display server" entry in issue template

- utilwebcam.js
Utilwebcam contains one translatable string which is used
when no webcam is specified. This currently causes a crash
of the preferences, because gettext is not imported in the
file.
This commit adds the gettext imports to utilwebcam.
> Fix crash when no webcam is selected and opening prefs

- extension.js
- prefs.js
- utilwebcam.js
Currently the extension prevents the Gnome Wayland session
from starting. This seems to be caused by GStreamer initializing
too early.
This commit delays the calls to GStreamer in the extension and
the preferences until the user interacts with the widgets. At that
time GStreamer is ready to be called and the extension works as
expected.
> Make extension work with Wayland

- utilaudio.js
Currently the function also sometimes returns false. Which
can lead to problems in calling functions.
Related issue: https://github.com/EasyScreenCast/EasyScreenCast/issues/180
> Make sure 'getListInputAudio' always returns an array

- utilwebcam.js
The 2nd parameter causes a warning.
Fixes: #176
> Remove 2nd parameter from Gst.Caps.new_empty_simple

- metadata.json
Hello,
I'm working on packaging this extension on Debian, based on Kali's work, and I see they are patching metadata.json to support gnome 3.30.
Thanks.
> [metadata.json] add support to 3.30

- utilaudio.js
Adds /usr/lib64/gnome-shell with GIRepository.Repository.prepend_search_path and GIRepository.Repository.prepend_library_path to properly import Gvc
> add lib64 to Gvc library/search path (fixes #207)

- extension.js
- prefs.js
- selection.js
Deprecate `Shell.GenericContainer` in `gnome-shell` 3.30
https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/153
Fix #224 #225
Actorized animation objects in `gnome-shell` 3.34
https://gitlab.gnome.org/GNOME/gnome-shell/commit/3d3dca4aa2e92f3b41bbd40e8bbc8992aeda1303
Fix #237 #238 #233
> Gnome 3.3x compatibility fix.

- utilexecmd.js
This addresses the following warning:
Some code called array.toString() on a Uint8Array instance. Previously
this would have interpreted the bytes of the array as a string, but that
is nonstandard. In the future this will return the bytes as
comma-separated digits. For the time being, the old behavior has been
preserved, but please fix your code anyway to explicitly call
ByteArray.toString(array).
Signed-off-by: Luiz Carvalho <lucarval@redhat.com>
> Use the standard ByteArray.toString conversion

- convenience.js
- extension.js
- metadata.json
- utilnotify.js
- utilrecorder.js
Fix for #275. I don't know if this will break older users however(?)
> Allow extension to load under GNOME 3.38

- Makefile
- convenience.js
- extension.js
- prefs.js
Example of a dev version. The extension version is 43, the actual version in package.json is 1.4.0 and there are two more commits landing at 54d9ce6 ...
> Display version in prefs dialog

- Options_UI.glade-gtk4
> Fix image size of ESC logo

- selection.js
Use Clutter.KEY_Escape instead of Clutter.Escape
`Clutter.Escape` does not exist for new clutter versions [1] [2] and `Clutter.KEY_Escape` exists for old Clutter versions [3], so this shall be a safe change
[1]: https://gjs-docs.gnome.org/clutter8~8_api/clutter.key_escape
[2]: https://gjs-docs.gnome.org/clutter8~8_api/clutter.escape
[3]: https://gjs-docs.gnome.org/clutter10~1.26.4/clutter.key_escape
> Fix [ESC] does not abort Window / Area Selection

- prefs.js
- utilrecorder.js
- utilwebcam.js
* Unroll framerates, if there are multiple options. Previously only one framerate was available.
* Fix filename pattern to avoid invalid filenames.
* Clear the capabilities list in the preferences before displaying/appending available capabilities.
* Fixes #316
> Only consider video/x-raw capabilities

- selection.js
- Fixes #325 
I tried to use the signal methods from GObject, but this didn't work out at all. So I kept the old `Signals.addSignalMethods` solution.
After that, the extension loaded, but no area could be selected. It has something to do with `Main.pushModal` which doesn't behave the same with gnome shell 42 anymore.
> Add missing toString methods in selection classes

- selection.js
Follows example code from https://gjs.guide/extensions/topics/session-modes.html#example-usage
> Remove sessionMode updated signal in Capture class

- CHANGELOG.md
- extension.js
MESSAGE_TRAY has been removed a couple of years ago already from gnome shell (https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/890a80902267befd30711770b8488072fcc8a9b7).
Allow keybinding in SYSTEM_MODAL mode.
Fixes #267
> Keybinding: Remove MESSAGE_TRAY, add SYSTEM_MODAL

- extension.js
- locale/ca.po
- locale/cs.po
- locale/de.po
- locale/easyscreencast.pot
- locale/es.po
- locale/fr.po
- locale/it.po
- locale/ja.po
- locale/pt_BR.po
- locale/ru.po
- locale/uk.po
- locale/vi.po
- locale/zh.po
- metadata.json
- selection.js
- utilnotify.js
- utilrecorder.js
I guess, this makes the extension now run only on Gnome Shell 46.
The notification stuff changed a lot...
Fixes #355
> Support Gnome 46

- convenience.js
- display_module.js
- selection.js
This is based off some review and the signal emitter guidelines I know
- export inline
- let instead of var
https://gjs.guide/extensions/upgrading/gnome-shell-43.html#signals
The ES6 constructors dont work when a type needs a name which is the util* files I think https://gjs.guide/guides/gobject/gtype.html#gtype-name
(I maintain the [Force Quit](https://github.com/meghprkh/force-quit) extension which has a copy of some of these files)
> Make some things more es6

- metadata.json
GNOME 47 is scheduled for release on Wednesday.
I did a very simple smoketest with this change on Debian with gnome-shell 47.rc
See also https://gjs.guide/extensions/upgrading/gnome-shell-47.html
> Support GNOME Shell 47

- metadata.json
I did a minimal test with GNOME Shell 48 Beta from Debian Experimental (GNOME Shell 48 Beta is also available in Ubuntu 25.04) and the extension seemed to work.
See https://gjs.guide/extensions/upgrading/gnome-shell-48.html
> Support GNOME Shell 48
